server:
  port: 9092
  error:
    include-stacktrace: never

spring:
  main:
    web-application-type: none
  security:
    user:
      password: secret

logging:
  level:
    root: info
    org:
      springframework:
        web: info
        batch: debug
        security: debug

library:
  server: http://localhost:9091/library-server


