services:

  keycloakx:
    build:
      context: "./keycloak"
      dockerfile: "./Dockerfile"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_LOG_LEVEL: INFO,org.infinispan:DEBUG,org.jgroups:DEBUG

      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-db
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public

      # Enable remote debugging
      DEBUG: "true"
      DEBUG_PORT: "*:8787"

      #KC_CACHE_CONFIG_FILE: cache-custom-jgroups.xml

      JAVA_OPTS: "-XX:MaxRAMPercentage=80 -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+DisableExplicitGC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -Djava.net.preferIPv4Stack=true"

      # Allow access via visualvm and jmc
      JAVA_TOOL_OPTIONS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8790 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: 2

    volumes:
      # This configures the key and certificate for HTTPS.
      - ./keycloak/mykeycloak.pem:/etc/x509/https/tls.crt:z
      - ./keycloak/mykeycloak-key.pem:/etc/x509/https/tls.key:z
      # Allow TLS connection to ourselves, this is necessary for cross realm Identity Brokering
      - ./keycloak/mykeycloak.pem:/etc/x509/ca/tls.crt:z
    command:
      - "--verbose"
      - "start"
      - "--auto-build"
      - "--https-certificate-file=/etc/x509/https/tls.crt"
      - "--https-certificate-key-file=/etc/x509/https/tls.key"
      - "--http-enabled=true"
      - "--http-relative-path=/auth"
      - "--http-port=8080"
      - "--proxy=passthrough"
# Note upcoming versions of Keycloak.X will leave out the port in the hostname parameter
      - "--hostname=mykeycloak:1443"

    ports:
      - "8080"
      - "8443"
      - "8787"
      - "8790"

  keycloak-db:
    image: mysql:5.7.38
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password 
    ports:
      - "3306"